### ISSUE TITLE
Initial startup errors

### ISSUE THREAD

**Issue by LesFerch** [brondavies/TrayToolbar#1]
If you click on the icon in system tray before going to Options to select a folder, there will be an error because the bundled JSON file incudes a path to your profile folder:
![image](https://github.com/brondavies/TrayToolbar/assets/79026235/a3840509-1c3d-46ba-ab85-67870c7c315b)

After selecting a folder of shortcuts and clicking Save, I get this error. I'm not sure what the problem is.
![image](https://github.com/brondavies/TrayToolbar/assets/79026235/47538b70-a8a1-40b8-819f-a614b5a7a172)

**Comment by brondavies** [comment]
Thanks.  I've updated the release to remove the configuration file that was there by mistake.  The initial launch should show the settings window automatically.
