### ISSUE TITLE
A number of questions

### ISSUE THREAD

**Issue by AlexLev59** [brondavies/TrayToolbar#10]
1. Although the utility is in the autoloader and accordingly is present in the notification area, but the first launch of the utility takes a very long time to display the menu.

2. Although I have 4 folders with subfolders selected in the utility settings, but only the first folder with subfolders is actually displayed in the menu.
![4](https://github.com/brondavies/TrayToolbar/assets/27947911/56106125-14be-4c11-b869-c912ebd5b6ad)
![3](https://github.com/brondavies/TrayToolbar/assets/27947911/d7c218a9-9af3-44c7-8e7e-0aa9b807ab74)
![2](https://github.com/brondavies/TrayToolbar/assets/27947911/ff59031e-d511-4630-a08a-1f997709bbe2)
![1](https://github.com/brondavies/TrayToolbar/assets/27947911/0e9037d4-1f77-425d-a9b0-e03972abba5d)

**Comment by brondavies** [comment]
Thank you for the feedback @AlexLev59 for the first issue, I think I can improve the initial load time.  The second issue reported is working as expected.  Each selected folder creates a separate icon in the system tray.  Look for the other icons that may be hidden under the system tray "additional icons" button.  Windows may hide these by default.

**Comment by brondavies** [comment]
Fixed in [v1.3.0](https://github.com/brondavies/TrayToolbar/releases/tag/v1.3.0)
