### ISSUE TITLE
[Enhancement] Some good ideas

### ISSUE THREAD

**Issue by SiTWulf** [brondavies/TrayToolbar#11]
I like to see these ideas

- Short results by Name (but Folders First)
- When click in link auto close Toolbar Window
- While the Follow desktop theme is implemented, please add a White/Dark Theme Selected from Settings.
- Ability to Mouse Scroll in toolbar windows

Some translations are really bad (For example in Spanish)
- "Open Folder" 
    "Carpeta abierta" is a bad translation. Corrected translation is: "Abrir Carpeta"
- "Save"
   "Ahorrar" is a bad translation. Corrected translation is: "Guardar"
- "TrayToolbar"
   "BandejaBarra de herramientas" is a bad translation. Corrected translation is: "Barra de herramientas de la bandeja" (But is this chase is really better not translate an leave it the original English Name)
- "Exit"
  "Salida" is a bad translation. Corrected translation is: "Salir"

**Comment by brondavies** [comment]
Thank you for the feedback and the corrections to the spanish translations - I'll roll those out in the next update.

**Comment by brondavies** [comment]
Added in [v1.3.0](https://github.com/brondavies/TrayToolbar/releases/tag/v1.3.0)
