### ISSUE TITLE
Right mouse button action

### ISSUE THREAD

**Issue by AlexLev59** [brondavies/TrayToolbar#14]
At a particular menu item, the action of the right and left mouse buttons is exactly the same - the selected file is launched.
But there are situations when you do not need to launch a specific menu item, but for example just copy the name of the executable file to the clipboard.
In this regard, I suggest: right-click the mouse and simply call the properties of the file.

**Comment by brondavies** [comment]
@AlexLev59 Thank you for the feedback. I'll try to get this added in the next update so that the system context menu is invoked on a right click.  This was also requested in issue https://github.com/brondavies/TrayToolbar/issues/8

**Comment by brondavies** [comment]
Added in [v1.3.2](https://github.com/brondavies/TrayToolbar/releases/tag/v1.3.2)

**Comment by AlexLev59** [comment]
I'm not sure if I've been understood correctly, because I'm using an electronic translator.
I have installed version 1.3.2, but I have not found the stated functionality.
For example, among the menu items I have a text file.
I right-click on it, expecting a system window of its properties to appear, but instead I have this file open the same way as with the left mouse button....
