### ISSUE TITLE
File extensions not listed

### ISSUE THREAD

**Issue by DeKnep** [brondavies/TrayToolbar#17]
Seen with v1.3.0 on Windows 11:

Files are always listed without their extension. It would help if that was only the case for shortcuts. Now I can only use the icon to guess which kind of file it is.
For all extensions other than .lnk, I suggest either following the Windows Explorer setting for showing extensions, or make it configurable.

**Comment by PebcakCity** [comment]
Agree with @DeKnep, if you are viewing a regular directory with more than `.lnk` files it's harder to tell what's what.  FWIW, I know some people keep "Hide file extensions for known file types" turned on in Explorer, but I personally can't stand that Windows feature so I disable it on every system I touch.

If you just want all extensions besides `.lnk` to be visible, you can have that by changing `SettingsForm.cs`'s `ReloadMenuItems(...)` method around line 259 ...
Comment out
```
Text = Path.GetFileNameWithoutExtension(file),
```
and make it:
```
Text = Path.GetFileName(file).Replace(".lnk", ""),
```
