### ISSUE TITLE
Minor Issues

### ISSUE THREAD

**Issue by LesFerch** [brondavies/TrayToolbar#2]
The ReadMe instructions are missing a step.

Currently:
- Run TrayToolbar.exe from this folder
- Select a folder containing your shortcuts

Should be something like this:
- Run TrayToolbar.exe from this folder
- Open your system tray, right-click the TrayToolbar icon, and select **Options**.
- Select a folder containing your shortcuts

The Exe and Dll properties details have some incorrect/missing information. It's cosmetic, but could cause some AV software to complain:
![image](https://github.com/brondavies/TrayToolbar/assets/79026235/84591aff-8571-4492-8411-983a31c25789)
![image](https://github.com/brondavies/TrayToolbar/assets/79026235/d91d695c-7dcd-4e9e-9b0a-e6daaba7a759)

**Comment by brondavies** [comment]
Fixed in #1
