### ISSUE TITLE
[Issue] No Icons for Folders Inside Folders + [Sugestions] No Shortcut Arrow & Bigger Font Size

### ISSUE THREAD

**Issue by Vv-82** [brondavies/TrayToolbar#22]
First this is a great little program and I want to say thank you for it, it's much better than the other guy's program too.

Issue:
1.  If I have a folder that has other folders inside it, those folders don't have icons displayed at all, just their name.

Suggestions: 
1. No Shortcut Arrows - it would look much better without them if you can do that.
2. Bigger Font Size & Icons - the size of the fonts & icons are too small compare to the default size in Windows 10, so a slightly bigger font I think would make the icons bigger too.

**Comment by brondavies** [comment]
Added in https://github.com/brondavies/TrayToolbar/releases/tag/v1.3.4
Icons on subfolders are not being implemented though.
