### ISSUE TITLE
Not working on ARM64?

### ISSUE THREAD

**Issue by ianc911** [brondavies/TrayToolbar#23]
Trying to run on Windows on ARM - 24H2 - 26100.1457. Installed the ARM version of .NET 8.3 from your download link (if I run the installer again it prompts to repair or uninstall), but when I try to run TrayToolbar.exe, it tells me 'You must install or update .NET to run this application'.

**Comment by brondavies** [comment]
I've added an ARM64 release build to the [download options](https://github.com/brondavies/TrayToolbar/releases/tag/v1.3.3).  Let me know if this solves the issue for you.

**Comment by ianc911** [comment]
That did indeed fix it. Thanks!
