### ISSUE TITLE
Shortcuts to folders - like menu folders

### ISSUE THREAD

**Issue by AlexLev59** [brondavies/TrayToolbar#26]
In Windows 11, Microsoft has now removed the functionality to create a Toolbar on the Taskbar.
And through this panel was a convenient way to access the Desktop.

I have a fantasy suggestion: Couldn't TrayToolbar be tweaked so that shortcuts to folders would stand as folders in the TrayToolbar menu?
I really don't want to add them via a separate button.

On my old Windows 11 24H2 computer, somehow I had a setting that allowed me to add Toolbars to the Taskbar, but I can't remember what tweaker I used to do it.

**Comment by brondavies** [comment]
This sounds just like the request in #24
I may add that as an option soon.

**Comment by AlexLev59** [comment]
v1.3.5: Shortcuts referring to folders (example c:\Users\Public\Desktop\) are not expanded into menu items. Request in #24 and #26. Currently - it just shows up as a shortcut link, followed by opening it in Explorer.
