### ISSUE TITLE
TrayToolbar-win-x64-portable-1.3.4 is unloaded from memory

### ISSUE THREAD

**Issue by AlexLev59** [brondavies/TrayToolbar#27]
The updated programme on Windows 24H2, after loading, gets unloaded from memory a couple of seconds after startup.
Even with the simplest contents of TrayToolbarConfig.json:
{
  ‘HideFileExtensions": false,
  ‘IgnoreAllDotFiles": false,
  ‘IgnoreFiles": [
    ‘.bak’,
    ‘.config’,
    ‘.dll’,
    ‘.ico’,
    ‘.ini’
  ],
  ‘IgnoreFolders": [
    ‘.git’,
    ‘.github’
  ],
  ‘MaxRecursionDepth": 3,
  ‘Theme": 0,
  ‘FontSize": 9,
  ‘LargeIcons": false,
  ‘Folders": [
    {
      ‘Name": “D:\-\-\\Test”,
      { ‘Recursive’: true
    }
  ]
}

Translated with www.DeepL.com/Translator (free version)

**Comment by SiTWulf** [comment]
Get the same problem.
Crash on a few seconds after launch.

The old version 1.3.3 Not have this problem.

**Comment by brondavies** [comment]
Thank you for the feedback.  This has been fixed in https://github.com/brondavies/TrayToolbar/releases/tag/v1.3.5

**Comment by SiTWulf** [comment]
Fixed.
Thanks
