### ISSUE TITLE
URL files (Steam desktop icons, for example) don't appear the same as App shortcuts

### ISSUE THREAD

**Issue by badken** [brondavies/TrayToolbar#29]
[Screenshot](https://i.imgur.com/AL0VJfM.png)

Need to drop the extension and read the icon from the URL shortcut, which is apparently different to reading the icon from a File Explorer shortcut.

**Comment by brondavies** [comment]
This is the same underlying problem described in #28

**Comment by brondavies** [comment]
Fixed in https://github.com/brondavies/TrayToolbar/releases/tag/v1.3.6
