### ISSUE TITLE
Error when trying to save the configuration

### ISSUE THREAD

**Issue by LesFerch** [brondavies/TrayToolbar#3]
Testing 1.1.1 on Windows 10 and I get this error when I click Save in Options:
![image](https://github.com/brondavies/TrayToolbar/assets/79026235/2e944d7b-a456-4e0a-8632-bb0d11a1004c)
I have full rights to that folder. I can create, change, and delete files there, so the error is very odd.

Since it's a portable program, I would prefer that it save the settings to the same folder as the exe and only go to the user's appdata folder if it cannot write to the current folder. Running the exe again opens another instance in the system tray. That could be useful if each copy could have its own configuration, so I think that's an argument for saving the settings with the exe.

**Comment by brondavies** [comment]
Thanks for sharing this.  It is possible that the file was open in another program at the time or that because the EXE was started twice, it couldn't share the json file.  I'll look at possible fixes and adding an option to save the configuration just with the EXE but the best practice is to treat folders with executables as not writable.

**Comment by LesFerch** [comment]
I checked again. I get the error with just one instance of TrayToolbar running.

**Comment by LesFerch** [comment]
I also just tested in a Windows 11 VM and got the same error.

**Comment by brondavies** [comment]
@LesFerch Can you try unmarking the EXE as blocked from File Explorer?  See instructions here: https://hotcakescommerce.zendesk.com/hc/en-us/articles/10932095222157-How-to-Unblock-File-Downloads#:~:text=Right%2Dclick%20on%20the%20file,Release%2003.08.00
I am just curious if this is preventing the app from writing to the folder.

**Comment by LesFerch** [comment]
The exe isn't blocked. Smartscreen would pop up if it were. I also verified that Traytoolbar.dll is not blocked. I've attached the Details from the error. It looks like you're getting an exception trying to delete a registry value that does not exist. Why that results in the access denied error is a bit strange, but maybe fixing the issue with the registry delete will clear that up.
[Error.txt](https://github.com/brondavies/TrayToolbar/files/15173579/Error.txt)

**Comment by brondavies** [comment]
This has been fixed in [v1.1.2](https://github.com/brondavies/TrayToolbar/releases/tag/v1.1.2)

**Comment by LesFerch** [comment]
Yup, the Save feature works fine for me now.

Just one small issue. The product version is showing as a floating point number and the "original file name" for the exe is TrayToolbar.dll instead of TrayToolbar.exe.

![image](https://github.com/brondavies/TrayToolbar/assets/79026235/3d7665e4-a5c0-41ee-a45c-1c0f3aed989f)

**Comment by brondavies** [comment]
> Just one small issue. The product version is showing as a floating point number and the "original file name" for the exe is TrayToolbar.dll instead of TrayToolbar.exe.

This is just a feature of the publishing mechanism that uses the git commit ID in the product version for attribution of the source code used when building the release.

**Comment by LesFerch** [comment]
Sounds like a bug. Product version should be "1.1.2.0" and original filename should be TrayToolbar.exe". It could matter for a script that audits installed software.
