### ISSUE TITLE
Multiple try icons with separate settings

### ISSUE THREAD

**Issue by little-fish** [brondavies/TrayToolbar#4]
Hi there.
Great tool!
Would it be possible to add an option to start multiple instances of the TrayToolbar with separate settings and custom tray icon? (Or single application instance with multiple tray icons (custom ones) with separate settings.)
Thanks.

**Comment by brondavies** [comment]
I think that's a great idea with just the ability to configure multiple icons.  Other people have suggested reading the entire folder structure into one menu with sub-menus.  Maybe we can do both in the next version

**Comment by little-fish** [comment]
My personal preference is to have separate icons for separate folders (its faster to launch specific file).
That would be great. Thank you.

**Comment by brondavies** [comment]
Multiple tray icons and directory tree support have been added in [v1.2.0](https://github.com/brondavies/TrayToolbar/releases/tag/v1.2.0)

**Comment by little-fish** [comment]
Works like a charm. Thank you!
