### ISSUE TITLE
German translation improvement

### ISSUE THREAD

**Issue by rockhock** [brondavies/TrayToolbar#5]
Hi, 
awsome Tool, and thanks for publishing it under an open licence for everyone to see the code and compile.

In the newest release there are some German translations that could be improved:

Exit -> Beenden (The current used word Ausfahrt is the word for Highway exit)
Folders -> Ordner
Cancel -> Abbrechen (Stornieren is more used for canceling a Hotel booking, not to cancel a IT interaction)
refresh -> Aktualisieren

All in all cosmetic issues, but i think this tool deserves it :)

**Comment by brondavies** [comment]
Thanks, the feedback helps a lot!

**Comment by brondavies** [comment]
Fixed in [v1.2.1](/brondavies/TrayToolbar/releases/tag/v1.2.1) release
