### ISSUE TITLE
[Enhancement] Follow Theme colors / Dark Mode

### ISSUE THREAD

**Issue by SiTWulf** [brondavies/TrayToolbar#6]
Please allow the window fly-outs to obey the current theme / dark mode colors.

**Comment by AlexLev59** [comment]
And the utility icon when the dark Windows theme is selected blends into the background.

**Comment by brondavies** [comment]
Thank you for the feedback.  I'll try to get this update in the next release.  As for the icon blending into the background @AlexLev59 - this could be a combination of settings affecting contrast but the folder icon that appears in the system tray can also be customized and comes from the shell icon used in file explorer.  If you customize the icon using the instructions [here](https://github.com/brondavies/TrayToolbar/tree/master?tab=readme-ov-file#customization) you can get an icon that has better contrast.

**Comment by brondavies** [comment]
Note: possibly waiting on https://github.com/dotnet/winforms/issues/7641

**Comment by brondavies** [comment]
Added in [v1.3.0](https://github.com/brondavies/TrayToolbar/releases/tag/v1.3.0)
