### ISSUE TITLE
This is not the same

### ISSUE THREAD

**Issue by Gruski** [brondavies/TrayToolbar#9]
Maybe I am missing something but I don't see a toolbar here. It's just a folder icon that you have to drill down into it. Is this how it was designed? Win 10 Toolbar showed all the icons in the task bar itself. Is this not how it's supposed to work?

**Comment by brondavies** [comment]
You are correct.  The Windows 11 extensibility model relies on widgets for the most part and we can't recreate the good ol' custom toolbar.  So, this is a near approximation that doesn't require elevated privileges, a total replacement for the task bar or a shell extension that would probably break down the road.
Some of these kind of utilities are listed here: https://www.reddit.com/r/Windows11/comments/16ow6ns/taskbar_replacement_enhancer_for_windows_11/
And some other hacks for the task bar are here: https://answers.microsoft.com/en-us/windows/forum/all/in-windows-11-how-can-you-add-a-toolbar-to-the/24394eb1-8787-479b-b50f-d4452443975a
